### ISSUE TITLE
Invalid AppStore link

### ISSUE THREAD

**Issue by CoRfr** [hotzjacobb/Weather-Santiago#1]
The link in the README.md seems invalid and links to the image, not the appstore.

**Comment by hotzjacobb** [comment]
Hi Bertrand,

Sorry about that. Thanks, I've corrected the link. Thanks for your time.

Kind regards,
Jacob 



On Tuesday, May 26, 2020, 04:43:05 PM PDT, Bertrand Roussel <notifications@github.com> wrote: 







The link in the README.md seems invalid and links to the image, not the appstore.
